const foodOrderDetails = [
  {
    id: 1,
    dishname: "Chicken Biryani",
    image:
      "https://b.zmtcdn.com/data/pictures/5/19753555/832960b89791c54c15f1141246a103e9_o2_featured_v2.jpg",
    description: "Chicken biryani with onion raita and salan.",
    category: "NON-VEG",
    price: 100,
    quantity: 0,
    isCart: false,
    totalPrice: 0,
    isSoldOut: false,
  },
  {
    id: 2,
    dishname: "Egg Biryani",
    image:
      "https://b.zmtcdn.com/data/pictures/6/20913576/d6eae8f22d67c64dbfdb5490f82149a3_o2_featured_v2.jpg",
    description: "Biryani with boiled egg cooked fresh.",
    category: "NON-VEG",
    price: 120,
    quantity: 0,
    isCart: false,
    totalPrice: 0,
    isSoldOut: false,
  },
  {
    id: 3,
    dishname: "Idli [2 Pieces]",
    image:
      "https://vaya.in/recipes/wp-content/uploads/2018/02/Idli-and-Sambar-1.jpg",
    description: "Super IDLI",
    category: "VEG",
    price: 50,
    quantity: 0,
    isCart: false,
    totalPrice: 0,
    isSoldOut: false,
  },

  {
    id: 4,
    dishname: "Plain Dosa",
    image:
      "https://b.zmtcdn.com/data/dish_photos/1f4/9f100dd714229362501d56a831d2e1f4.jpg?output-format=webp",
    description: "Super Plain Dosa",
    category: "VEG",
    price: 25,
    quantity: 0,
    isCart: false,
    totalPrice: 0,
    isSoldOut: false,
  },
  {
    id: 5,
    dishname: "Coffee",
    image:
      "https://b.zmtcdn.com/data/dish_photos/fa4/a6e6d0f6671449c69c4fe0a143ce2fa4.jpg",
    description: "Super Coffee",
    category: "Beverages",
    price: 12,
    quantity: 0,
    isCart: false,
    totalPrice: 0,
    isSoldOut: false,
  },
  {
    id: 6,
    dishname: "Tea",
    image:
      "https://b.zmtcdn.com/data/dish_photos/296/1e490f9917f442d204e2b3b8ed907296.jpg?output-format=webp",
    description: "Super Tea",
    category: "Beverages",
    price: 10,
    quantity: 0,
    isCart: false,
    totalPrice: 0,
    isSoldOut: false,
  },
  {
    id: 7,
    dishname: "Cheese Pizza",
    image:
      "https://b.zmtcdn.com/data/dish_photos/287/c8b41694d98a4c2f4e812b94221be287.jpg",
    description: "Super Cheese Pizza",
    category: "Snacks",
    price: 50,
    quantity: 0,
    isCart: false,
    totalPrice: 0,
    isSoldOut: false,
  },
  {
    id: 8,
    dishname: "Chicken Burger",
    image: "https://img.lovepik.com/photo/48005/9759.jpg_wh860.jpg",
    description: "Super Chicken Burger",
    category: "Snacks",
    price: 25,
    quantity: 0,
    isCart: false,
    totalPrice: 0,
    isSoldOut: false,
  },
];

export default foodOrderDetails;
